[package]
name = "rtrs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand  = "*"
rayon = "1.5"

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = 'abort'
codegen-units = 1
